name: "Main"
on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: false # don't cancel all jobs if some of them failed
      matrix:
        node: ["10", "12", "14"]
    name: Test
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn test

  release:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event_name == 'push' && github.ref != 'refs/heads/master' && contains(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
